"""KTrain Strict Profile 레이아웃 수치 SSOT.

DESKTOP_UI_DESIGN_RULES.md §8/§13 기준. 페이지·카드·스플리터 등 모든
GUI 코드는 임의 수치를 쓰지 말고 이 모듈 상수를 사용한다.
"""

WINDOW_DEFAULT_WIDTH = 1100
WINDOW_DEFAULT_HEIGHT = 800
WINDOW_MIN_WIDTH = 640
WINDOW_MIN_HEIGHT = 560
SCREEN_MARGIN = 40

# 페이지 여백
PAGE_MARGIN = 24
WORK_PAGE_MARGIN = 16

# 간격 스케일 (4/8/12/16/24/32 중 선택)
SPACE_XXS = 4
SPACE_XS = 8
SPACE_SM = 12
SPACE_MD = 16
SPACE_LG = 24
SPACE_XL = 32

DEFAULT_SPACING = 8
SECTION_SPACING = 16

# 작업 화면 (QSplitter + HeaderCardWidget)
CARD_VIEW_MARGINS = (12, 8, 12, 12)
SPLITTER_HANDLE_WIDTH = 8
CONDITION_PANEL_MIN_WIDTH = 400
RESULT_PANEL_MIN_WIDTH = 360

# 상태/표시
PROGRESS_RING_SIZE = 28
TABLE_ROW_MIN_HEIGHT = 40

# List : Detail 기본 비율
LIST_DETAIL_STRETCH = (1, 2)

__all__ = [
    "CARD_VIEW_MARGINS",
    "CONDITION_PANEL_MIN_WIDTH",
    "DEFAULT_SPACING",
    "LIST_DETAIL_STRETCH",
    "PAGE_MARGIN",
    "PROGRESS_RING_SIZE",
    "RESULT_PANEL_MIN_WIDTH",
    "SCREEN_MARGIN",
    "SECTION_SPACING",
    "SPACE_LG",
    "SPACE_MD",
    "SPACE_SM",
    "SPACE_XL",
    "SPACE_XS",
    "SPACE_XXS",
    "SPLITTER_HANDLE_WIDTH",
    "TABLE_ROW_MIN_HEIGHT",
    "WINDOW_DEFAULT_HEIGHT",
    "WINDOW_DEFAULT_WIDTH",
    "WINDOW_MIN_HEIGHT",
    "WINDOW_MIN_WIDTH",
    "WORK_PAGE_MARGIN",
]
